name 'takipi_storage'
maintainer 'OverOps'
maintainer_email 'support@overops.com'
license 'All Rights Reserved'
description 'Installs/Configures takipi_storage'
version '0.1.0'
chef_version '>= 15.0'
issues_url 'https://github.com/overops/chef-cookbooks/issues'
source_url 'https://github.com/overops/chef-cookbooks'
